on: push
name: Test
jobs:
  test:
    name:    Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1' ]

    steps:
      - uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install Dependencies
        run: composer install

      - name: Check configuration
        run: php data/bin/check_configuration.php

      - name: Test
        run: php data/bin/symfony symfony:test --trace
